spring:
  application:
    name: leader-election

server:
  port: 8080

app:
  role: coordinator
  pod-id: coordinator-1
  coordinator-url: http://localhost:8080
  application-port: 8081

logging:
  level:
    com.leaderelection: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

