spring:
  application:
    name: leader-election-pod5

server:
  port: 8085

app:
  role: application
  pod-id: app-pod-5
  coordinator-url: http://localhost:8080
  application-port: 8085

logging:
  level:
    com.leaderelection: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

